modLoader="javafml"
issueTrackerURL="https://github.com/NimajnebEC/auto-elytra/issues"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="autoelytra"
version="${version}"
displayName="Auto Elytra"
authors="NimajnebEC"
displayTest="IGNORE_ALL_VERSION"
displayURL="https://github.com/NimajnebEC/auto-elytra"
logoFile="icon.png"
logoBlur=false

description='''
A client side mod that automatically switches your elytra and chestplate when you go to fly.
'''


[[dependencies.autoelytra]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"


[[dependencies.autoelytra]]
   modId="minecraft"
   mandatory=true
   versionRange="1.20.4"
   ordering="NONE"
   side="BOTH"
